on: [push, pull_request]
name: Test & Build
jobs:
  test_and_build:
    strategy:
      matrix:
        go-version: [1.11.x, 1.12.x, 1.13.x, 1.14.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run tests
      run: |
        go test -race -coverprofile=coverage.txt -covermode=atomic
        curl -s https://codecov.io/bash -t ${{secrets.CODECOV_TOKEN}} | bash
      shell: bash
    - name: Build
      run: go build